export interface Location {
  slug: string
  city: string
  headline: string
  description: string
  metaTitle: string
  metaDescription: string
  neighborhoods: string[]
  areasLabel: string
}

export const locations: Location[] = [
  // ── Inner Boston neighborhoods ────────────────────────────────────────────
  {
    slug: 'movers-allston-ma',
    city: 'Allston',
    headline: 'Allston moves on your terms.',
    description: 'Allston is one of the densest rental markets in Greater Boston — high turnover, tight hallways, and September 1st chaos. NoTimeMover handles it all. Set your budget before we reach out.',
    metaTitle: 'Movers in Allston, MA — NoTimeMover | Set Your Price',
    metaDescription: "Allston's rental market moves fast. NoTimeMover is ready — set your budget upfront, no surprise quotes. Fully insured crew for walk-ups and tight hallways.",
    neighborhoods: ['Brighton', 'Back Bay', 'Fenway', 'Cambridge', 'Brookline', 'Mission Hill', 'Watertown', 'South End'],
    areasLabel: 'Allston & nearby neighborhoods',
  },
  {
    slug: 'movers-back-bay-ma',
    city: 'Back Bay',
    headline: 'Back Bay moves on your terms.',
    description: 'Back Bay brownstones, narrow staircases, and street parking make every move a logistics challenge. NoTimeMover knows the neighborhood. Set your price and we handle the rest.',
    metaTitle: 'Movers in Back Bay, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Back Bay brownstones and tight streets require a crew that knows what they\'re doing. Set your price upfront — fully insured, same-day response.',
    neighborhoods: ['South End', 'Fenway', 'Beacon Hill', 'Allston', 'Brookline', 'Kenmore', 'Newbury St', 'Copley'],
    areasLabel: 'Back Bay & surrounding areas',
  },
  {
    slug: 'movers-brighton-ma',
    city: 'Brighton',
    headline: 'Brighton moves on your terms.',
    description: 'Brighton is packed with students, young professionals, and apartment buildings that turn over every September. NoTimeMover is built for this market. Set your budget, we do the rest.',
    metaTitle: 'Movers in Brighton, MA — NoTimeMover | Local & Fast',
    metaDescription: 'Brighton apartment moves, September 1st rush or any time of year. Set your price before we contact you — fully insured crew, same-day response.',
    neighborhoods: ['Allston', 'Newton', 'Brookline', 'Watertown', 'Oak Square', 'Cleveland Circle', 'Chestnut Hill', 'Back Bay'],
    areasLabel: 'Brighton & nearby areas',
  },
  {
    slug: 'movers-charlestown-ma',
    city: 'Charlestown',
    headline: 'Charlestown moves on your terms.',
    description: 'Charlestown townhouses, Navy Yard condos, and the historic streets between — NoTimeMover moves them all. You set the price, we confirm what it covers.',
    metaTitle: 'Movers in Charlestown, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Charlestown townhouses and Navy Yard condos. NoTimeMover handles the move — set your price upfront, no surprise fees. Fully insured, same-day response.',
    neighborhoods: ['North End', 'East Boston', 'Cambridge', 'Somerville', 'Bunker Hill', 'Sullivan Square', 'Downtown Boston', 'Back Bay'],
    areasLabel: 'Charlestown & nearby neighborhoods',
  },
  {
    slug: 'movers-dorchester-ma',
    city: 'Dorchester',
    headline: 'Dorchester moves on your terms.',
    description: 'Dorchester is Boston\'s largest neighborhood and one of its most active moving markets. Whether you\'re moving within Dot or heading out, NoTimeMover has you covered.',
    metaTitle: 'Movers in Dorchester, MA — NoTimeMover | Your Price',
    metaDescription: 'Dorchester moving made simple. Set your budget before we call — no hourly surprises. Fully insured crew serving all of Dorchester and Greater Boston.',
    neighborhoods: ['South Boston', 'Roxbury', 'Mattapan', 'Milton', 'Hyde Park', 'Jamaica Plain', 'Quincy', 'Braintree'],
    areasLabel: 'Dorchester & surrounding areas',
  },
  {
    slug: 'movers-east-boston-ma',
    city: 'East Boston',
    headline: 'East Boston moves on your terms.',
    description: 'Eastie is growing fast — new builds, renovated triple-deckers, and a steady stream of new residents. NoTimeMover serves East Boston with fully insured crews and same-day response.',
    metaTitle: 'Movers in East Boston, MA — NoTimeMover | Set Your Price',
    metaDescription: 'East Boston movers, fully insured. Set your price before we contact you — new builds, triple-deckers, any size move. Same-day response.',
    neighborhoods: ['Charlestown', 'Winthrop', 'Revere', 'Chelsea', 'South Boston', 'Airport District', 'Maverick', 'Downtown Boston'],
    areasLabel: 'East Boston & nearby areas',
  },
  {
    slug: 'movers-fenway-ma',
    city: 'Fenway',
    headline: 'Fenway moves on your terms.',
    description: 'Fenway\'s dense student population and high apartment turnover make it one of Boston\'s busiest moving zones. NoTimeMover is ready — you set the price, we show up.',
    metaTitle: 'Movers in Fenway, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Fenway movers for apartments, studios, and student moves. Set your budget upfront — fully insured crew, walk-ups welcome, same-day response.',
    neighborhoods: ['Back Bay', 'Allston', 'Mission Hill', 'Kenmore', 'Brookline', 'South End', 'Jamaica Plain', 'Longwood'],
    areasLabel: 'Fenway & nearby neighborhoods',
  },
  {
    slug: 'movers-jamaica-plain-ma',
    city: 'Jamaica Plain',
    headline: 'Jamaica Plain moves on your terms.',
    description: 'JP\'s mix of Victorian homes, condos, and apartments draws a steady flow of movers year-round. NoTimeMover covers the whole neighborhood and beyond.',
    metaTitle: 'Movers in Jamaica Plain, MA — NoTimeMover | Your Budget',
    metaDescription: 'Jamaica Plain movers for Victorians, condos, and apartments. Set your price before we contact you — fully insured, same-day response.',
    neighborhoods: ['Roxbury', 'Roslindale', 'West Roxbury', 'Mission Hill', 'Fenway', 'Brookline', 'Hyde Park', 'South End'],
    areasLabel: 'Jamaica Plain & surrounding areas',
  },
  {
    slug: 'movers-south-boston-ma',
    city: 'South Boston',
    headline: 'South Boston moves on your terms.',
    description: 'Southie has one of the highest apartment turnover rates in the city — especially September 1st. NoTimeMover handles Seaport condos and triple-deckers equally.',
    metaTitle: 'Movers in South Boston, MA — NoTimeMover | Set Your Price',
    metaDescription: 'South Boston movers for Seaport condos and Southie triple-deckers. Set your price upfront — fully insured crew, September 1st ready.',
    neighborhoods: ['Dorchester', 'Roxbury', 'East Boston', 'Downtown Boston', 'Seaport', 'South End', 'Quincy', 'Milton'],
    areasLabel: 'South Boston & nearby areas',
  },
  {
    slug: 'movers-south-end-ma',
    city: 'South End',
    headline: 'South End moves on your terms.',
    description: 'The South End\'s Victorian rowhouses and converted brownstones are beautiful — and a challenge to move in and out of. NoTimeMover\'s crew knows the drill.',
    metaTitle: 'Movers in South End, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'South End brownstones and rowhouses handled with care. Set your price before we contact you — fully insured, same-day response, no surprise fees.',
    neighborhoods: ['Back Bay', 'Roxbury', 'Dorchester', 'Fenway', 'South Boston', 'Beacon Hill', 'Chinatown', 'Jamaica Plain'],
    areasLabel: 'South End & surrounding neighborhoods',
  },
  {
    slug: 'movers-roxbury-ma',
    city: 'Roxbury',
    headline: 'Roxbury moves on your terms.',
    description: 'Roxbury is central Boston — close to everything, dense, and active. NoTimeMover serves Roxbury and the surrounding neighborhoods with a fully insured crew.',
    metaTitle: 'Movers in Roxbury, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Roxbury movers, fully insured. Set your budget before we call — no surprise quotes. Serving Roxbury and all of Greater Boston, same-day response.',
    neighborhoods: ['Dorchester', 'Jamaica Plain', 'South End', 'Mission Hill', 'Mattapan', 'South Boston', 'Hyde Park', 'Fenway'],
    areasLabel: 'Roxbury & nearby neighborhoods',
  },
  {
    slug: 'movers-mission-hill-ma',
    city: 'Mission Hill',
    headline: 'Mission Hill moves on your terms.',
    description: 'Mission Hill\'s steep streets and dense apartments are home to one of Boston\'s biggest student populations. NoTimeMover handles walk-ups and tight spaces without charging extra.',
    metaTitle: 'Movers in Mission Hill, MA — NoTimeMover | Your Price',
    metaDescription: 'Mission Hill apartment movers — walk-ups, no stair fees. Set your price upfront, fully insured crew, same-day response. Student moves welcome.',
    neighborhoods: ['Fenway', 'Jamaica Plain', 'Roxbury', 'Brookline', 'Allston', 'Back Bay', 'South End', 'Longwood'],
    areasLabel: 'Mission Hill & surrounding areas',
  },
  {
    slug: 'movers-hyde-park-ma',
    city: 'Hyde Park',
    headline: 'Hyde Park moves on your terms.',
    description: 'Hyde Park is one of Boston\'s most residential neighborhoods — larger homes, more furniture, and longer drives. NoTimeMover handles it all without surprise fees.',
    metaTitle: 'Movers in Hyde Park, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Hyde Park movers for houses, condos, and apartments. Set your budget before we call — fully insured crew, same-day response, no hourly surprises.',
    neighborhoods: ['Roslindale', 'West Roxbury', 'Mattapan', 'Canton', 'Dedham', 'Milton', 'Jamaica Plain', 'Dorchester'],
    areasLabel: 'Hyde Park & nearby areas',
  },
  {
    slug: 'movers-roslindale-ma',
    city: 'Roslindale',
    headline: 'Roslindale moves on your terms.',
    description: 'Roslindale\'s quiet streets and family homes don\'t move as chaotically as inner Boston — but they still need a crew that shows up on time and works clean.',
    metaTitle: 'Movers in Roslindale, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Roslindale movers for houses, apartments, and condos. You set the price — fully insured, same-day response, no surprise fees on move day.',
    neighborhoods: ['Jamaica Plain', 'Hyde Park', 'West Roxbury', 'Dedham', 'Mattapan', 'Dorchester', 'Forest Hills', 'Arnold Arboretum'],
    areasLabel: 'Roslindale & surrounding areas',
  },
  {
    slug: 'movers-west-roxbury-ma',
    city: 'West Roxbury',
    headline: 'West Roxbury moves on your terms.',
    description: 'West Roxbury\'s single-family homes and tree-lined streets are some of Boston\'s most sought-after real estate. NoTimeMover handles residential moves with care.',
    metaTitle: 'Movers in West Roxbury, MA — NoTimeMover | Your Budget',
    metaDescription: 'West Roxbury residential movers. Set your price before we contact you — fully insured crew, same-day response. Houses and condos welcome.',
    neighborhoods: ['Roslindale', 'Hyde Park', 'Jamaica Plain', 'Dedham', 'Needham', 'Newton', 'Brookline', 'Chestnut Hill'],
    areasLabel: 'West Roxbury & nearby areas',
  },
  // ── Greater Boston suburbs ────────────────────────────────────────────────
  {
    slug: 'movers-boston-ma',
    city: 'Boston',
    headline: 'Boston moves on your terms.',
    description: 'Boston\'s busiest moving day is September 1st — but NoTimeMover is ready year-round. Set your budget before we contact you, skip the surprise quotes, and get moving.',
    metaTitle: 'Movers in Boston, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Boston\'s busiest moving day is September 1st. NoTimeMover is ready — set your budget upfront, skip the surprise quotes. Fully insured crew, walk-ups welcome.',
    neighborhoods: ['Back Bay', 'South End', 'Allston', 'Brighton', 'Fenway', 'Charlestown', 'Jamaica Plain', 'Dorchester', 'Somerville', 'Cambridge'],
    areasLabel: 'Boston neighborhoods & beyond',
  },
  {
    slug: 'movers-cambridge-ma',
    city: 'Cambridge',
    headline: 'Cambridge moves on your terms.',
    description: 'Home to Harvard, MIT, and one of the densest apartment markets in New England. Cambridge triple-deckers, high-rises, and student moves are NoTimeMover\'s specialty.',
    metaTitle: 'Movers in Cambridge, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Moving near Harvard or MIT? Cambridge triple-deckers and high-rises are our specialty. Set your price upfront — fully insured crew, same-day response.',
    neighborhoods: ['Somerville', 'Arlington', 'Belmont', 'Watertown', 'Allston', 'Brighton', 'Boston', 'Medford'],
    areasLabel: 'Cambridge & nearby neighborhoods',
  },
  {
    slug: 'movers-somerville-ma',
    city: 'Somerville',
    headline: 'Somerville moves on your terms.',
    description: 'Somerville is one of the most densely populated cities in the US — triple-deckers stacked on top of each other, Green Line stops, and a thriving arts crowd that moves often.',
    metaTitle: 'Movers in Somerville, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Somerville triple-deckers and condos. Set your price before we contact you — fully insured crew, no stair fees, same-day response.',
    neighborhoods: ['Cambridge', 'Medford', 'Arlington', 'Malden', 'Everett', 'Charlestown', 'Boston', 'Davis Square'],
    areasLabel: 'Somerville & nearby areas',
  },
  {
    slug: 'movers-brookline-ma',
    city: 'Brookline',
    headline: 'Brookline moves on your terms.',
    description: 'Brookline\'s leafy streets, large homes, and proximity to Boston make it one of Greater Boston\'s most active moving markets. NoTimeMover serves Brookline with a fully insured crew.',
    metaTitle: 'Movers in Brookline, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Brookline movers for houses, condos, and apartments. Set your budget upfront — fully insured crew, same-day response, no surprise fees.',
    neighborhoods: ['Newton', 'Back Bay', 'Allston', 'Brighton', 'Fenway', 'Jamaica Plain', 'West Roxbury', 'Chestnut Hill'],
    areasLabel: 'Brookline & surrounding areas',
  },
  {
    slug: 'movers-newton-ma',
    city: 'Newton',
    headline: 'Newton moves on your terms.',
    description: 'Newton\'s 13 villages and large residential homes mean bigger moves, more furniture, and more logistics. NoTimeMover handles Newton moves without hourly billing surprises.',
    metaTitle: 'Movers in Newton, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Newton movers for large homes, condos, and apartments across all 13 villages. Set your price before we call — fully insured, same-day response.',
    neighborhoods: ['Brookline', 'Waltham', 'Needham', 'Wellesley', 'West Roxbury', 'Chestnut Hill', 'Watertown', 'Brighton'],
    areasLabel: 'Newton & surrounding neighborhoods',
  },
  {
    slug: 'movers-quincy-ma',
    city: 'Quincy',
    headline: 'Quincy moves on your terms.',
    description: 'Quincy is one of the fastest-growing cities south of Boston — new condos downtown, family neighborhoods further out. NoTimeMover covers all of Quincy and the South Shore.',
    metaTitle: 'Movers in Quincy, MA — NoTimeMover | Your Price',
    metaDescription: 'Quincy movers for condos, apartments, and houses. Set your price upfront — fully insured crew, same-day response. Serving Quincy and the South Shore.',
    neighborhoods: ['Braintree', 'Milton', 'Dorchester', 'South Boston', 'Weymouth', 'Randolph', 'Holbrook', 'Hingham'],
    areasLabel: 'Quincy & South Shore areas',
  },
  {
    slug: 'movers-medford-ma',
    city: 'Medford',
    headline: 'Medford moves on your terms.',
    description: 'Medford sits right at the crossroads of several major commuter corridors — close to Somerville, Cambridge, and Malden. NoTimeMover serves Medford with a fully insured crew.',
    metaTitle: 'Movers in Medford, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Medford movers, fully insured. Set your budget before we call — no surprise quotes. Serving Medford, Somerville, Malden, and all of Greater Boston.',
    neighborhoods: ['Somerville', 'Cambridge', 'Malden', 'Arlington', 'Everett', 'Woburn', 'Winchester', 'Tufts University area'],
    areasLabel: 'Medford & nearby areas',
  },
  {
    slug: 'movers-malden-ma',
    city: 'Malden',
    headline: 'Malden moves on your terms.',
    description: 'Malden is one of Greater Boston\'s most diverse and active rental markets — affordable, Orange Line connected, and always moving. NoTimeMover is built for this.',
    metaTitle: 'Movers in Malden, MA — NoTimeMover | Affordable & Fast',
    metaDescription: 'Malden movers on your terms. Set your price before we contact you — fully insured crew, same-day response. Serving Malden and Greater Boston.',
    neighborhoods: ['Medford', 'Somerville', 'Everett', 'Revere', 'Saugus', 'Woburn', 'Melrose', 'Malden Center'],
    areasLabel: 'Malden & surrounding areas',
  },
  {
    slug: 'movers-everett-ma',
    city: 'Everett',
    headline: 'Everett moves on your terms.',
    description: 'Everett has transformed rapidly over the past few years — new developments, a booming restaurant scene, and a steady flow of residents coming and going.',
    metaTitle: 'Movers in Everett, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Everett movers — new builds and older apartments. Set your price before we reach out — fully insured, same-day response, no surprise fees.',
    neighborhoods: ['Somerville', 'Malden', 'Chelsea', 'East Boston', 'Revere', 'Medford', 'Charlestown', 'Encore area'],
    areasLabel: 'Everett & nearby areas',
  },
  {
    slug: 'movers-revere-ma',
    city: 'Revere',
    headline: 'Revere moves on your terms.',
    description: 'Revere Beach is the backdrop, but the city itself is a dense, growing rental market with strong demand for reliable movers. NoTimeMover serves Revere and the North Shore.',
    metaTitle: 'Movers in Revere, MA — NoTimeMover | Local & Insured',
    metaDescription: 'Revere movers, fully insured. Set your price before we contact you — same-day response, no stair fees. Serving Revere and the North Shore.',
    neighborhoods: ['East Boston', 'Chelsea', 'Everett', 'Malden', 'Winthrop', 'Saugus', 'Lynn', 'Beachmont'],
    areasLabel: 'Revere & nearby areas',
  },
  {
    slug: 'movers-chelsea-ma',
    city: 'Chelsea',
    headline: 'Chelsea moves on your terms.',
    description: 'Chelsea is one of Greater Boston\'s most affordable cities — but it\'s changing fast. NoTimeMover serves Chelsea\'s apartments and condos with a fully insured crew.',
    metaTitle: 'Movers in Chelsea, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Chelsea movers, fully insured. Set your budget upfront — no hourly surprises. Serving Chelsea, East Boston, Revere, and all of Greater Boston.',
    neighborhoods: ['East Boston', 'Revere', 'Everett', 'Somerville', 'Charlestown', 'Winthrop', 'Malden', 'Downtown Boston'],
    areasLabel: 'Chelsea & nearby areas',
  },
  {
    slug: 'movers-waltham-ma',
    city: 'Waltham',
    headline: 'Waltham moves on your terms.',
    description: 'Waltham is a dense suburb with Brandeis University, a massive biotech corridor, and a steady flow of apartments turning over every year. NoTimeMover covers it all.',
    metaTitle: 'Movers in Waltham, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Waltham movers for apartments, condos, and houses. Set your price before we call — fully insured, same-day response. Brandeis and beyond.',
    neighborhoods: ['Newton', 'Watertown', 'Belmont', 'Arlington', 'Lexington', 'Needham', 'Wellesley', 'Brighton'],
    areasLabel: 'Waltham & surrounding areas',
  },
  {
    slug: 'movers-watertown-ma',
    city: 'Watertown',
    headline: 'Watertown moves on your terms.',
    description: 'Watertown sits between Cambridge, Newton, and Waltham — a convenient spot for commuters and a growing condo market. NoTimeMover has you covered.',
    metaTitle: 'Movers in Watertown, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Watertown movers for condos and apartments. Set your price upfront — fully insured crew, same-day response. Between Cambridge, Newton, and Waltham.',
    neighborhoods: ['Cambridge', 'Newton', 'Waltham', 'Arlington', 'Belmont', 'Brighton', 'Allston', 'Brookline'],
    areasLabel: 'Watertown & nearby areas',
  },
  {
    slug: 'movers-arlington-ma',
    city: 'Arlington',
    headline: 'Arlington moves on your terms.',
    description: 'Arlington is one of the most desirable towns between Cambridge and Lexington — family-friendly, great schools, and a constant flow of new residents each year.',
    metaTitle: 'Movers in Arlington, MA — NoTimeMover | Your Price',
    metaDescription: 'Arlington movers for houses, condos, and apartments. Set your budget before we call — fully insured crew, same-day response, no surprise fees.',
    neighborhoods: ['Cambridge', 'Belmont', 'Lexington', 'Medford', 'Somerville', 'Watertown', 'Waltham', 'Winchester'],
    areasLabel: 'Arlington & nearby towns',
  },
  {
    slug: 'movers-belmont-ma',
    city: 'Belmont',
    headline: 'Belmont moves on your terms.',
    description: 'Belmont is a quiet residential town with large homes and an affluent commuter base. NoTimeMover handles Belmont moves with the care they deserve — no surprise fees.',
    metaTitle: 'Movers in Belmont, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Belmont movers for houses and condos. Set your price before we contact you — fully insured, same-day response, no hourly billing surprises.',
    neighborhoods: ['Cambridge', 'Arlington', 'Watertown', 'Waltham', 'Lexington', 'Medford', 'Somerville', 'Brighton'],
    areasLabel: 'Belmont & nearby towns',
  },
  {
    slug: 'movers-needham-ma',
    city: 'Needham',
    headline: 'Needham moves on your terms.',
    description: 'Needham\'s high home values and large floor plans mean bigger moves. NoTimeMover handles full house moves, condo relocations, and everything in between — you set the price.',
    metaTitle: 'Movers in Needham, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Needham movers for full house and condo moves. Set your budget upfront — fully insured crew, same-day response, no hidden fees on move day.',
    neighborhoods: ['Newton', 'Dedham', 'Wellesley', 'West Roxbury', 'Brookline', 'Natick', 'Norwood', 'Walpole'],
    areasLabel: 'Needham & surrounding towns',
  },
  {
    slug: 'movers-dedham-ma',
    city: 'Dedham',
    headline: 'Dedham moves on your terms.',
    description: 'Dedham is a growing suburb southwest of Boston — easy highway access, solid schools, and a steady housing market that keeps movers busy year-round.',
    metaTitle: 'Movers in Dedham, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Dedham movers for houses, condos, and apartments. Set your price before we call — fully insured, same-day response, no stair fees.',
    neighborhoods: ['Norwood', 'Needham', 'West Roxbury', 'Milton', 'Westwood', 'Canton', 'Hyde Park', 'Roslindale'],
    areasLabel: 'Dedham & nearby towns',
  },
  {
    slug: 'movers-braintree-ma',
    city: 'Braintree',
    headline: 'Braintree moves on your terms.',
    description: 'Braintree is the southern anchor of the Red Line — great highway access, solid neighborhoods, and a mix of condos and single-family homes that turn over regularly.',
    metaTitle: 'Movers in Braintree, MA — NoTimeMover | Your Price',
    metaDescription: 'Braintree movers for condos, houses, and apartments. Set your budget upfront — fully insured crew, same-day response. South Shore and Boston.',
    neighborhoods: ['Quincy', 'Weymouth', 'Randolph', 'Milton', 'Holbrook', 'Norwell', 'Avon', 'Holbrook'],
    areasLabel: 'Braintree & South Shore areas',
  },
  {
    slug: 'movers-milton-ma',
    city: 'Milton',
    headline: 'Milton moves on your terms.',
    description: 'Milton sits between Boston and Quincy — quiet, suburban, and full of large family homes. NoTimeMover handles residential moves in Milton without hourly billing surprises.',
    metaTitle: 'Movers in Milton, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Milton residential movers for houses and condos. Set your price before we contact you — fully insured, same-day response, no surprise fees.',
    neighborhoods: ['Quincy', 'Dorchester', 'Hyde Park', 'Braintree', 'Canton', 'Stoughton', 'Randolph', 'East Milton'],
    areasLabel: 'Milton & nearby towns',
  },
  {
    slug: 'movers-lynn-ma',
    city: 'Lynn',
    headline: 'Lynn moves on your terms.',
    description: 'Lynn is one of the North Shore\'s most affordable cities and one of its most active rental markets. NoTimeMover serves Lynn with a fully insured crew and same-day response.',
    metaTitle: 'Movers in Lynn, MA — NoTimeMover | Affordable & Insured',
    metaDescription: 'Lynn movers, fully insured. Set your budget before we call — no hourly surprises. Serving Lynn, Saugus, Peabody, and the North Shore.',
    neighborhoods: ['Saugus', 'Peabody', 'Salem', 'Revere', 'Malden', 'Everett', 'Swampscott', 'Nahant'],
    areasLabel: 'Lynn & North Shore areas',
  },
  {
    slug: 'movers-winthrop-ma',
    city: 'Winthrop',
    headline: 'Winthrop moves on your terms.',
    description: 'Winthrop is a small peninsula town east of Boston with a tight-knit community and a limited supply of housing that drives steady moving demand.',
    metaTitle: 'Movers in Winthrop, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Winthrop movers, fully insured. Set your price before we contact you — same-day response, no hidden fees. East of Boston, close to Logan.',
    neighborhoods: ['East Boston', 'Revere', 'Chelsea', 'Everett', 'Malden', 'Swampscott', 'Lynn', 'Beachmont'],
    areasLabel: 'Winthrop & nearby areas',
  },
  {
    slug: 'movers-woburn-ma',
    city: 'Woburn',
    headline: 'Woburn moves on your terms.',
    description: 'Woburn is a fast-growing suburb north of Boston — close to Route 128, with new apartment complexes and established neighborhoods all moving regularly.',
    metaTitle: 'Movers in Woburn, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Woburn movers for apartments, condos, and houses. Set your price before we call — fully insured crew, same-day response, no surprise fees.',
    neighborhoods: ['Medford', 'Malden', 'Burlington', 'Winchester', 'Stoneham', 'Lexington', 'Woburn Center', 'Wilmington'],
    areasLabel: 'Woburn & nearby towns',
  },
  {
    slug: 'movers-burlington-ma',
    city: 'Burlington',
    headline: 'Burlington moves on your terms.',
    description: 'Burlington is a thriving Route 128 suburb — lots of new apartment development, proximity to tech campuses, and a steady flow of residents moving in and out.',
    metaTitle: 'Movers in Burlington, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Burlington movers for new apartments and established homes. Set your budget upfront — fully insured, same-day response, no hourly billing surprises.',
    neighborhoods: ['Woburn', 'Lexington', 'Wilmington', 'Bedford', 'Billerica', 'Waltham', 'Stoneham', 'Route 128 corridor'],
    areasLabel: 'Burlington & nearby towns',
  },
  {
    slug: 'movers-lexington-ma',
    city: 'Lexington',
    headline: 'Lexington moves on your terms.',
    description: 'Lexington is one of Greater Boston\'s most prestigious suburbs — large homes, top-rated schools, and a housing market that keeps movers busy. NoTimeMover handles it with care.',
    metaTitle: 'Movers in Lexington, MA — NoTimeMover | Your Budget',
    metaDescription: 'Lexington movers for large homes and condos. Set your price before we contact you — fully insured crew, same-day response, no hidden fees.',
    neighborhoods: ['Arlington', 'Belmont', 'Waltham', 'Burlington', 'Bedford', 'Concord', 'Lincoln', 'Winchester'],
    areasLabel: 'Lexington & surrounding towns',
  },
  {
    slug: 'movers-framingham-ma',
    city: 'Framingham',
    headline: 'Framingham moves on your terms.',
    description: 'Framingham is a hub city along Route 9 — a mix of apartments, condos, and single-family homes that makes it one of MetroWest\'s busiest moving markets.',
    metaTitle: 'Movers in Framingham, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Framingham movers for apartments, condos, and houses. Set your price before we call — fully insured crew, same-day response, MetroWest and beyond.',
    neighborhoods: ['Natick', 'Ashland', 'Sudbury', 'Marlborough', 'Southborough', 'Holliston', 'Hopkinton', 'Sherborn'],
    areasLabel: 'Framingham & MetroWest areas',
  },
  {
    slug: 'movers-natick-ma',
    city: 'Natick',
    headline: 'Natick moves on your terms.',
    description: 'Natick is a growing MetroWest town with a mix of new condos, classic New England homes, and a steady flow of residents relocating to and from Greater Boston.',
    metaTitle: 'Movers in Natick, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Natick movers for condos, houses, and apartments. Set your budget upfront — fully insured crew, same-day response, no surprise fees on move day.',
    neighborhoods: ['Framingham', 'Wellesley', 'Needham', 'Ashland', 'Wayland', 'Sherborn', 'Holliston', 'Route 9 corridor'],
    areasLabel: 'Natick & MetroWest towns',
  },
  {
    slug: 'movers-wellesley-ma',
    city: 'Wellesley',
    headline: 'Wellesley moves on your terms.',
    description: 'Wellesley is one of the most desirable towns in Greater Boston — large homes, Wellesley College, and a housing market that demands a crew you can trust.',
    metaTitle: 'Movers in Wellesley, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Wellesley movers for large homes and condos. Set your price before we contact you — fully insured crew, same-day response, handled with care.',
    neighborhoods: ['Needham', 'Newton', 'Natick', 'Weston', 'Dedham', 'Westwood', 'Dover', 'Route 9 corridor'],
    areasLabel: 'Wellesley & surrounding towns',
  },
  {
    slug: 'movers-peabody-ma',
    city: 'Peabody',
    headline: 'Peabody moves on your terms.',
    description: 'Peabody is one of the North Shore\'s largest cities — affordable housing, good highway access, and a steady rental market. NoTimeMover serves Peabody with same-day response.',
    metaTitle: 'Movers in Peabody, MA — NoTimeMover | Your Price',
    metaDescription: 'Peabody movers, fully insured. Set your budget before we call — no hourly surprises. Serving Peabody, Salem, Beverly, and the North Shore.',
    neighborhoods: ['Salem', 'Beverly', 'Lynn', 'Danvers', 'Marblehead', 'Swampscott', 'Saugus', 'Topsfield'],
    areasLabel: 'Peabody & North Shore areas',
  },
  {
    slug: 'movers-salem-ma',
    city: 'Salem',
    headline: 'Salem moves on your terms.',
    description: 'Salem is one of the most vibrant cities on the North Shore — historic, dense, and growing. NoTimeMover handles Salem\'s Victorian homes, condos, and apartments alike.',
    metaTitle: 'Movers in Salem, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Salem movers for Victorians, condos, and apartments. Set your price upfront — fully insured crew, same-day response. North Shore covered.',
    neighborhoods: ['Peabody', 'Beverly', 'Marblehead', 'Swampscott', 'Lynn', 'Danvers', 'Ipswich', 'Hamilton'],
    areasLabel: 'Salem & North Shore areas',
  },
  {
    slug: 'movers-beverly-ma',
    city: 'Beverly',
    headline: 'Beverly moves on your terms.',
    description: 'Beverly is a growing North Shore city with a mix of commuters, artists, and families. NoTimeMover serves Beverly with a fully insured crew and no-nonsense pricing.',
    metaTitle: 'Movers in Beverly, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Beverly movers, fully insured. Set your price before we contact you — same-day response, no hidden fees. North Shore and Greater Boston.',
    neighborhoods: ['Salem', 'Peabody', 'Danvers', 'Wenham', 'Hamilton', 'Gloucester', 'Manchester', 'Marblehead'],
    areasLabel: 'Beverly & North Shore towns',
  },
  // ── Extended MA ───────────────────────────────────────────────────────────
  {
    slug: 'movers-worcester-ma',
    city: 'Worcester',
    headline: 'Worcester moves on your terms.',
    description: 'Worcester is Massachusetts\' second-largest city — home to Clark, WPI, Holy Cross, and a large apartment market. NoTimeMover handles Worcester moves without hourly billing surprises.',
    metaTitle: 'Movers in Worcester, MA — NoTimeMover | Set Your Price',
    metaDescription: "Worcester's second-largest city deserves straightforward moving. Set your budget before we call — no hourly surprises. Fully insured crew, same-day response.",
    neighborhoods: ['Shrewsbury', 'Millbury', 'Auburn', 'Grafton', 'Northborough', 'Westborough', 'Paxton', 'Holden'],
    areasLabel: 'Worcester & surrounding cities',
  },
  {
    slug: 'movers-lowell-ma',
    city: 'Lowell',
    headline: 'Lowell moves on your terms.',
    description: 'Lowell is a diverse, growing city along the Merrimack — UMass Lowell, a revitalized downtown, and a large rental market. NoTimeMover serves Lowell with same-day response.',
    metaTitle: 'Movers in Lowell, MA — NoTimeMover | Local & Affordable',
    metaDescription: 'Moving near UMass Lowell or anywhere in the Mill City? Set your budget upfront and we tell you exactly what it covers. Fully insured crew, same-day response.',
    neighborhoods: ['Chelmsford', 'Dracut', 'Tewksbury', 'Billerica', 'Wilmington', 'Methuen', 'Lawrence', 'Haverhill'],
    areasLabel: 'Lowell & Merrimack Valley areas',
  },
  {
    slug: 'movers-springfield-ma',
    city: 'Springfield',
    headline: 'Springfield moves on your terms.',
    description: 'Springfield is the anchor of Western Massachusetts — the biggest city for 100 miles in any direction and a major hub for both local and out-of-state moves.',
    metaTitle: 'Movers in Springfield, MA — NoTimeMover | Your Budget',
    metaDescription: "Western MA's movers for local and out-of-state moves. Set your price before we reach out — no surprise quotes. Fully insured, same-day response.",
    neighborhoods: ['Chicopee', 'Holyoke', 'Ludlow', 'Agawam', 'West Springfield', 'Longmeadow', 'East Longmeadow', 'Wilbraham'],
    areasLabel: 'Springfield & Pioneer Valley areas',
  },
  {
    slug: 'movers-lawrence-ma',
    city: 'Lawrence',
    headline: 'Lawrence moves on your terms.',
    description: 'Lawrence is a dense Merrimack Valley city with one of the most active rental markets in the region. NoTimeMover handles Lawrence moves quickly and without surprise fees.',
    metaTitle: 'Movers in Lawrence, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Lawrence movers, fully insured. Set your price before we call — no surprise quotes, same-day response. Serving Lawrence and the Merrimack Valley.',
    neighborhoods: ['Methuen', 'Andover', 'North Andover', 'Haverhill', 'Lowell', 'Salem NH', 'Bradford', 'Dracut'],
    areasLabel: 'Lawrence & Merrimack Valley areas',
  },
  {
    slug: 'movers-haverhill-ma',
    city: 'Haverhill',
    headline: 'Haverhill moves on your terms.',
    description: 'Haverhill is a growing Merrimack Valley city with a revitalized downtown and an active housing market. NoTimeMover serves Haverhill with fully insured crews.',
    metaTitle: 'Movers in Haverhill, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Haverhill movers, fully insured. Set your budget before we contact you — same-day response, no surprise fees. Merrimack Valley covered.',
    neighborhoods: ['Lawrence', 'Methuen', 'Bradford', 'Amesbury', 'Salisbury', 'Newburyport', 'Groveland', 'Plaistow NH'],
    areasLabel: 'Haverhill & nearby towns',
  },
  {
    slug: 'movers-brockton-ma',
    city: 'Brockton',
    headline: 'Brockton moves on your terms.',
    description: 'Brockton is one of the most populous cities in southeastern Massachusetts — a large, diverse rental market with steady moving demand year-round.',
    metaTitle: 'Movers in Brockton, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Brockton movers, fully insured. Set your price before we call — no hourly surprises, same-day response. Serving Brockton and southeastern MA.',
    neighborhoods: ['Stoughton', 'Avon', 'Easton', 'West Bridgewater', 'Bridgewater', 'Abington', 'Whitman', 'Randolph'],
    areasLabel: 'Brockton & southeastern MA areas',
  },
  {
    slug: 'movers-new-bedford-ma',
    city: 'New Bedford',
    headline: 'New Bedford moves on your terms.',
    description: 'New Bedford is the largest city on the SouthCoast — a historic whaling city with a large working-class rental market and strong moving demand throughout the year.',
    metaTitle: 'Movers in New Bedford, MA — NoTimeMover | Your Price',
    metaDescription: 'New Bedford movers, fully insured. Set your budget upfront — no surprise fees, same-day response. SouthCoast MA covered.',
    neighborhoods: ['Dartmouth', 'Fairhaven', 'Acushnet', 'Fall River', 'Taunton', 'Wareham', 'Marion', 'Mattapoisett'],
    areasLabel: 'New Bedford & SouthCoast areas',
  },
  {
    slug: 'movers-fall-river-ma',
    city: 'Fall River',
    headline: 'Fall River moves on your terms.',
    description: 'Fall River sits right on the Rhode Island border — close enough to Providence for out-of-state demand and large enough for a thriving local rental market.',
    metaTitle: 'Movers in Fall River, MA — NoTimeMover | Set Your Price',
    metaDescription: 'Fall River movers, fully insured. Set your price before we contact you — same-day response, no hidden fees. MA/RI border and beyond.',
    neighborhoods: ['New Bedford', 'Taunton', 'Swansea', 'Somerset', 'Dighton', 'Seekonk', 'Attleboro', 'Providence RI area'],
    areasLabel: 'Fall River & SouthCoast areas',
  },
  {
    slug: 'movers-taunton-ma',
    city: 'Taunton',
    headline: 'Taunton moves on your terms.',
    description: 'Taunton is a growing city at the crossroads of southeastern Massachusetts — midway between Boston, Providence, and New Bedford, with a steady housing market.',
    metaTitle: 'Movers in Taunton, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Taunton movers, fully insured. Set your budget upfront — no hourly surprises, same-day response. Southeastern MA and beyond.',
    neighborhoods: ['Brockton', 'Raynham', 'Easton', 'Norton', 'Berkley', 'Dighton', 'Bridgewater', 'Attleboro'],
    areasLabel: 'Taunton & southeastern MA areas',
  },
  {
    slug: 'movers-plymouth-ma',
    city: 'Plymouth',
    headline: 'Plymouth moves on your terms.',
    description: 'Plymouth is America\'s hometown and one of the fastest-growing towns on the South Shore — new construction, waterfront condos, and a busy seasonal moving market.',
    metaTitle: 'Movers in Plymouth, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Plymouth movers for new construction and established homes. Set your price before we call — fully insured, same-day response, South Shore covered.',
    neighborhoods: ['Kingston', 'Duxbury', 'Marshfield', 'Wareham', 'Carver', 'Middleborough', 'Pembroke', 'Hanson'],
    areasLabel: 'Plymouth & South Shore towns',
  },
]

export function getLocation(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug)
}

export function getAllSlugs(): string[] {
  return locations.map((l) => l.slug)
}
