export interface Location {
  slug: string
  city: string
  headline: string
  description: string
  metaTitle: string
  metaDescription: string
  neighborhoods: string[]
  areasLabel: string
  transit: string
  housingStock: string
  driveTime: string
}

export const locations: Location[] = [
  // ── Inner Boston neighborhoods ────────────────────────────────────────────
  {
    slug: 'movers-allston-ma',
    city: 'Allston',
    headline: 'Allston moves on your terms.',
    description: 'Allston is one of the densest rental markets in Greater Boston — high turnover, tight hallways, and September 1st chaos. NoTimeMover handles it all. Set your budget before we reach out.',
    metaTitle: 'Movers in Allston, MA — NoTimeMover | No Surprise Fees',
    metaDescription: "Allston's rental market moves fast. NoTimeMover is ready — set your budget upfront, no surprise quotes. Fully insured crew for walk-ups and tight hallways.",
    neighborhoods: ['Brighton', 'Back Bay', 'Fenway', 'Cambridge', 'Brookline', 'Mission Hill', 'Watertown', 'South End'],
    areasLabel: 'Allston & nearby neighborhoods',
    transit: 'Green Line B branch (Packard\'s Corner, Harvard Ave, Allston St)',
    housingStock: 'Dense multi-family triple-deckers and student apartment buildings',
    driveTime: '~10 min from downtown Boston',
  },
  {
    slug: 'movers-back-bay-ma',
    city: 'Back Bay',
    headline: 'Back Bay moves on your terms.',
    description: 'Back Bay brownstones, narrow staircases, and street parking make every move a logistics challenge. NoTimeMover knows the neighborhood. Tell us your budget and we handle the rest.',
    metaTitle: 'Movers in Back Bay, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Back Bay brownstones and tight streets require a crew that knows what they\'re doing. Set your budget upfront — fully insured, same-day response.',
    neighborhoods: ['South End', 'Fenway', 'Beacon Hill', 'Allston', 'Brookline', 'Kenmore', 'Newbury St', 'Copley'],
    areasLabel: 'Back Bay & surrounding areas',
    transit: 'Orange Line (Back Bay), Green Line (Copley, Arlington, Hynes)',
    housingStock: 'Historic brownstones and converted rowhouse apartments with narrow stairwells',
    driveTime: '~5 min from downtown Boston',
  },
  {
    slug: 'movers-brighton-ma',
    city: 'Brighton',
    headline: 'Brighton moves on your terms.',
    description: 'Brighton is packed with students, young professionals, and apartment buildings that turn over every September. NoTimeMover is built for this market. Set your budget, we do the rest.',
    metaTitle: 'Movers in Brighton, MA — NoTimeMover | Local & Fast',
    metaDescription: 'Brighton apartment moves, September 1st rush or any time of year. Set your budget before we call — fully insured crew, same-day response.',
    neighborhoods: ['Allston', 'Newton', 'Brookline', 'Watertown', 'Oak Square', 'Cleveland Circle', 'Chestnut Hill', 'Back Bay'],
    areasLabel: 'Brighton & nearby areas',
    transit: 'Green Line B branch (Washington St, Sutherland Rd, Chestnut Hill Ave)',
    housingStock: 'Triple-deckers and large apartment complexes with heavy September turnover',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-charlestown-ma',
    city: 'Charlestown',
    headline: 'Charlestown moves on your terms.',
    description: 'Charlestown townhouses, Navy Yard condos, and the historic streets between — NoTimeMover moves them all. Tell us your budget, we confirm what it covers.',
    metaTitle: 'Movers in Charlestown, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Charlestown townhouses and Navy Yard condos. NoTimeMover handles the move — set your budget upfront, no surprise fees. Fully insured, same-day response.',
    neighborhoods: ['North End', 'East Boston', 'Cambridge', 'Somerville', 'Bunker Hill', 'Sullivan Square', 'Downtown Boston', 'Back Bay'],
    areasLabel: 'Charlestown & nearby neighborhoods',
    transit: 'Orange Line (Community College), plus MBTA ferry to Long Wharf',
    housingStock: 'Federal-era townhouses alongside newer Navy Yard condo buildings',
    driveTime: '~8 min from downtown Boston',
  },
  {
    slug: 'movers-dorchester-ma',
    city: 'Dorchester',
    headline: 'Dorchester moves on your terms.',
    description: 'Dorchester is Boston\'s largest neighborhood and one of its most active moving markets. Whether you\'re moving within Dot or heading out, NoTimeMover has you covered.',
    metaTitle: 'Movers in Dorchester, MA — NoTimeMover | Your Price',
    metaDescription: 'Dorchester moving made simple. Set your budget before we call — no hourly surprises. Fully insured crew serving all of Dorchester and Greater Boston.',
    neighborhoods: ['South Boston', 'Roxbury', 'Mattapan', 'Milton', 'Hyde Park', 'Jamaica Plain', 'Quincy', 'Braintree'],
    areasLabel: 'Dorchester & surrounding areas',
    transit: 'Red Line Ashmont branch, plus the Fairmount Line commuter rail',
    housingStock: 'Boston\'s largest stock of triple-deckers, spread across a wide area',
    driveTime: '~10-15 min from downtown Boston',
  },
  {
    slug: 'movers-east-boston-ma',
    city: 'East Boston',
    headline: 'East Boston moves on your terms.',
    description: 'Eastie is growing fast — new builds, renovated triple-deckers, and a steady stream of new residents. NoTimeMover serves East Boston with fully insured crews and same-day response.',
    metaTitle: 'Movers in East Boston, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'East Boston movers, fully insured. Set your budget before we call — new builds, triple-deckers, any size move. Same-day response.',
    neighborhoods: ['Charlestown', 'Winthrop', 'Revere', 'Chelsea', 'South Boston', 'Airport District', 'Maverick', 'Downtown Boston'],
    areasLabel: 'East Boston & nearby areas',
    transit: 'Blue Line (Maverick, Airport, Wood Island, Orient Heights)',
    housingStock: 'Triple-deckers alongside new waterfront condo development',
    driveTime: '~8 min from downtown Boston via the Sumner/Callahan Tunnel',
  },
  {
    slug: 'movers-fenway-ma',
    city: 'Fenway',
    headline: 'Fenway moves on your terms.',
    description: 'Fenway\'s dense student population and high apartment turnover make it one of Boston\'s busiest moving zones. NoTimeMover is ready — tell us your budget, we show up.',
    metaTitle: 'Movers in Fenway, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Fenway movers for apartments, studios, and student moves. Set your budget upfront — fully insured crew, walk-ups welcome, same-day response.',
    neighborhoods: ['Back Bay', 'Allston', 'Mission Hill', 'Kenmore', 'Brookline', 'South End', 'Jamaica Plain', 'Longwood'],
    areasLabel: 'Fenway & nearby neighborhoods',
    transit: 'Green Line D/E branches (Fenway, Longwood)',
    housingStock: 'Dense student apartment buildings near Fenway Park and the Longwood Medical Area',
    driveTime: '~7 min from downtown Boston',
  },
  {
    slug: 'movers-jamaica-plain-ma',
    city: 'Jamaica Plain',
    headline: 'Jamaica Plain moves on your terms.',
    description: 'JP\'s mix of Victorian homes, condos, and apartments draws a steady flow of movers year-round. NoTimeMover covers the whole neighborhood and beyond.',
    metaTitle: 'Movers in Jamaica Plain, MA — NoTimeMover | Your Budget',
    metaDescription: 'Jamaica Plain movers for Victorians, condos, and apartments. Set your budget before we call — fully insured, same-day response.',
    neighborhoods: ['Roxbury', 'Roslindale', 'West Roxbury', 'Mission Hill', 'Fenway', 'Brookline', 'Hyde Park', 'South End'],
    areasLabel: 'Jamaica Plain & surrounding areas',
    transit: 'Orange Line (Stony Brook, Green St, Forest Hills)',
    housingStock: 'Victorian triple-deckers, single-families near Jamaica Pond, and newer condos',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-south-boston-ma',
    city: 'South Boston',
    headline: 'South Boston moves on your terms.',
    description: 'Southie has one of the highest apartment turnover rates in the city — especially September 1st. NoTimeMover handles Seaport condos and triple-deckers equally.',
    metaTitle: 'Movers in South Boston, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'South Boston movers for Seaport condos and Southie triple-deckers. Set your budget upfront — fully insured crew, September 1st ready.',
    neighborhoods: ['Dorchester', 'Roxbury', 'East Boston', 'Downtown Boston', 'Seaport', 'South End', 'Quincy', 'Milton'],
    areasLabel: 'South Boston & nearby areas',
    transit: 'Red Line (Broadway, Andrew), plus the Silver Line to Seaport',
    housingStock: 'Classic Southie triple-deckers alongside new Seaport high-rises',
    driveTime: '~8 min from downtown Boston',
  },
  {
    slug: 'movers-south-end-ma',
    city: 'South End',
    headline: 'South End moves on your terms.',
    description: 'The South End\'s Victorian rowhouses and converted brownstones are beautiful — and a challenge to move in and out of. NoTimeMover\'s crew knows the drill.',
    metaTitle: 'Movers in South End, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'South End brownstones and rowhouses handled with care. Set your budget before we call — fully insured, same-day response, no surprise fees.',
    neighborhoods: ['Back Bay', 'Roxbury', 'Dorchester', 'Fenway', 'South Boston', 'Beacon Hill', 'Chinatown', 'Jamaica Plain'],
    areasLabel: 'South End & surrounding neighborhoods',
    transit: 'Orange Line (Back Bay, Tufts Medical Center), plus the Silver Line',
    housingStock: 'Victorian brick rowhouses and converted brownstone apartments',
    driveTime: '~6 min from downtown Boston',
  },
  {
    slug: 'movers-roxbury-ma',
    city: 'Roxbury',
    headline: 'Roxbury moves on your terms.',
    description: 'Roxbury is central Boston — close to everything, dense, and active. NoTimeMover serves Roxbury and the surrounding neighborhoods with a fully insured crew.',
    metaTitle: 'Movers in Roxbury, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Roxbury movers, fully insured. Set your budget before we call — no surprise quotes. Serving Roxbury and all of Greater Boston, same-day response.',
    neighborhoods: ['Dorchester', 'Jamaica Plain', 'South End', 'Mission Hill', 'Mattapan', 'South Boston', 'Hyde Park', 'Fenway'],
    areasLabel: 'Roxbury & nearby neighborhoods',
    transit: 'Orange Line (Roxbury Crossing, Ruggles), plus the Fairmount Line',
    housingStock: 'Mix of triple-deckers and newer multi-family developments',
    driveTime: '~8 min from downtown Boston',
  },
  {
    slug: 'movers-mission-hill-ma',
    city: 'Mission Hill',
    headline: 'Mission Hill moves on your terms.',
    description: 'Mission Hill\'s steep streets and dense apartments are home to one of Boston\'s biggest student populations. NoTimeMover handles walk-ups and tight spaces without charging extra.',
    metaTitle: 'Movers in Mission Hill, MA — NoTimeMover | Your Price',
    metaDescription: 'Mission Hill apartment movers — walk-ups, no stair fees. Set your budget upfront, fully insured crew, same-day response. Student moves welcome.',
    neighborhoods: ['Fenway', 'Jamaica Plain', 'Roxbury', 'Brookline', 'Allston', 'Back Bay', 'South End', 'Longwood'],
    areasLabel: 'Mission Hill & surrounding areas',
    transit: 'Orange Line (Roxbury Crossing), Green Line E branch nearby',
    housingStock: 'Dense student and medical-worker apartment buildings on steep streets',
    driveTime: '~8 min from downtown Boston',
  },
  {
    slug: 'movers-hyde-park-ma',
    city: 'Hyde Park',
    headline: 'Hyde Park moves on your terms.',
    description: 'Hyde Park is one of Boston\'s most residential neighborhoods — larger homes, more furniture, and longer drives. NoTimeMover handles it all without surprise fees.',
    metaTitle: 'Movers in Hyde Park, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Hyde Park movers for houses, condos, and apartments. Set your budget before we call — fully insured crew, same-day response, no hourly surprises.',
    neighborhoods: ['Roslindale', 'West Roxbury', 'Mattapan', 'Canton', 'Dedham', 'Milton', 'Jamaica Plain', 'Dorchester'],
    areasLabel: 'Hyde Park & nearby areas',
    transit: 'Fairmount and Franklin Line commuter rail (Hyde Park, Readville)',
    housingStock: 'Larger single- and two-family homes — Boston\'s most suburban neighborhood',
    driveTime: '~18 min from downtown Boston',
  },
  {
    slug: 'movers-roslindale-ma',
    city: 'Roslindale',
    headline: 'Roslindale moves on your terms.',
    description: 'Roslindale\'s quiet streets and family homes don\'t move as chaotically as inner Boston — but they still need a crew that shows up on time and works clean.',
    metaTitle: 'Movers in Roslindale, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Roslindale movers for houses, apartments, and condos. No surprise fees — fully insured, same-day response, no hidden charges on move day.',
    neighborhoods: ['Jamaica Plain', 'Hyde Park', 'West Roxbury', 'Dedham', 'Mattapan', 'Dorchester', 'Forest Hills', 'Arnold Arboretum'],
    areasLabel: 'Roslindale & surrounding areas',
    transit: 'Needham Line commuter rail (Roslindale Village)',
    housingStock: 'Single- and multi-family homes around a walkable village center',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-west-roxbury-ma',
    city: 'West Roxbury',
    headline: 'West Roxbury moves on your terms.',
    description: 'West Roxbury\'s single-family homes and tree-lined streets are some of Boston\'s most sought-after real estate. NoTimeMover handles residential moves with care.',
    metaTitle: 'Movers in West Roxbury, MA — NoTimeMover | Your Budget',
    metaDescription: 'West Roxbury residential movers. Set your budget before we call — fully insured crew, same-day response. Houses and condos welcome.',
    neighborhoods: ['Roslindale', 'Hyde Park', 'Jamaica Plain', 'Dedham', 'Needham', 'Newton', 'Brookline', 'Chestnut Hill'],
    areasLabel: 'West Roxbury & nearby areas',
    transit: 'Needham Line commuter rail (West Roxbury, Highland)',
    housingStock: 'Single-family homes on tree-lined streets — Boston\'s most suburban feel',
    driveTime: '~18 min from downtown Boston',
  },
  {
    slug: 'movers-beacon-hill-ma',
    city: 'Beacon Hill',
    headline: 'Beacon Hill moves on your terms.',
    description: "Gas lamps, brick sidewalks, and streets too narrow for a standard moving truck. Beacon Hill is one of Boston's toughest neighborhoods to move into — NoTimeMover knows how to work around the constraints without passing the headache on to you.",
    metaTitle: 'Movers in Beacon Hill, Boston MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Beacon Hill movers for narrow streets, brownstones, and walk-ups. Set your budget before we call — fully insured, no stair fees, same-day response.',
    neighborhoods: ['Back Bay', 'North End', 'Downtown Boston', 'West End', 'Cambridge Street', 'Government Center', 'Bowdoin Square', 'Louisburg Square'],
    areasLabel: 'Beacon Hill & surrounding areas',
    transit: 'Red/Green Line (Park St, Charles/MGH)',
    housingStock: 'Historic brick rowhouses on narrow, largely car-free streets',
    driveTime: '~3 min from downtown Boston',
  },
  {
    slug: 'movers-north-end-ma',
    city: 'North End',
    headline: 'North End moves on your terms.',
    description: "Boston's North End runs on one of the oldest street grids in the country — narrow alleys, essentially no parking, and walk-up apartments that haven't changed much since the 1800s. NoTimeMover handles North End moves without stair fees or surprise charges.",
    metaTitle: 'Movers in North End, Boston MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'North End Boston movers for narrow streets and walk-ups. No stair fees. Set your budget before we call — fully insured, same-day response.',
    neighborhoods: ['Beacon Hill', 'Charlestown', 'East Boston', 'Downtown Boston', 'Waterfront', 'Government Center', 'Haymarket', 'West End'],
    areasLabel: 'North End & surrounding neighborhoods',
    transit: 'Green/Orange Line (Haymarket)',
    housingStock: 'Pre-war walk-up apartments on some of the oldest streets in the US',
    driveTime: '~3 min from downtown Boston',
  },
  {
    slug: 'movers-seaport-ma',
    city: 'Seaport',
    headline: 'Seaport moves on your terms.',
    description: "The Seaport District is one of Boston's newest neighborhoods — wide streets, modern loading docks, and luxury towers built for convenience. NoTimeMover handles Seaport condos and apartments without the luxury markup on the moving side.",
    metaTitle: 'Movers in Seaport District, Boston MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Seaport District Boston movers for luxury condos and new apartment buildings. Set your budget upfront — fully insured, COI available, same-day response.',
    neighborhoods: ['South Boston', 'Downtown Boston', 'South End', 'Fort Point', 'Financial District', 'East Boston', 'Chinatown', 'Congress Street area'],
    areasLabel: 'Seaport & South Boston Waterfront',
    transit: 'Silver Line (World Trade Center, Courthouse)',
    housingStock: 'New-construction high-rises with elevators and loading docks',
    driveTime: '~5 min from downtown Boston',
  },
  {
    slug: 'movers-chinatown-ma',
    city: 'Chinatown',
    headline: 'Chinatown moves on your terms.',
    description: "Boston's Chinatown is dense and compact — a mix of walk-up apartments, mid-rises, and older buildings packed in between the South End, Downtown, and the Theater District. NoTimeMover serves Chinatown without stair fees or minimum charges.",
    metaTitle: 'Movers in Chinatown, Boston MA — NoTimeMover | Your Price',
    metaDescription: 'Chinatown Boston movers for apartments and condos. Set your budget before we call — fully insured crew, no stair fees, same-day response.',
    neighborhoods: ['South End', 'Downtown Boston', 'Seaport', 'Back Bay', 'Theater District', 'South Boston', 'Roxbury', 'Bay Village'],
    areasLabel: 'Chinatown & surrounding neighborhoods',
    transit: 'Orange Line (Chinatown, Tufts Medical Center), plus the Silver Line',
    housingStock: 'Dense mix of walk-ups and mid-rise apartment buildings',
    driveTime: '~4 min from downtown Boston',
  },
  {
    slug: 'movers-downtown-boston-ma',
    city: 'Downtown Boston',
    headline: 'Downtown Boston moves on your terms.',
    description: "Downtown Boston has a growing condo market with strict building management rules to match. NoTimeMover is fully insured and can provide a certificate of liability for any building that requires one — no back-and-forth, no delay on move day.",
    metaTitle: 'Movers in Downtown Boston, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Downtown Boston movers for condos and high-rises. COI available on request. Set your budget upfront — fully insured, same-day response.',
    neighborhoods: ['Beacon Hill', 'Back Bay', 'Seaport', 'Chinatown', 'South End', 'North End', 'Financial District', 'Midtown'],
    areasLabel: 'Downtown Boston & Financial District',
    transit: 'Red, Orange, Green, and Blue Lines converge (Park St, Downtown Crossing, State)',
    housingStock: 'High-rise condos, including converted office and historic buildings',
    driveTime: '0 min — downtown Boston',
  },
  {
    slug: 'movers-mattapan-ma',
    city: 'Mattapan',
    headline: 'Mattapan moves on your terms.',
    description: "Mattapan is one of Boston's largest residential neighborhoods — triple-deckers, single-family homes, and a steady flow of renters and owners who just need a reliable crew. NoTimeMover serves Mattapan with the same fully insured team it sends anywhere in Boston.",
    metaTitle: 'Movers in Mattapan, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Mattapan movers for triple-deckers, houses, and apartments. Set your budget before we call — fully insured crew, same-day response, no hidden fees.',
    neighborhoods: ['Dorchester', 'Hyde Park', 'Roxbury', 'Jamaica Plain', 'Milton', 'Roslindale', 'Blue Hill Avenue area', 'Readville'],
    areasLabel: 'Mattapan & surrounding neighborhoods',
    transit: 'Mattapan Trolley (High-Speed Line), plus the Fairmount Line',
    housingStock: 'Triple-deckers and single-family homes across Boston\'s southern edge',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-kenmore-square-ma',
    city: 'Kenmore Square',
    headline: 'Kenmore Square moves on your terms.',
    description: "Kenmore Square sits right between BU, Fenway Park, and the Green Line — one of Boston's busiest student neighborhoods. September 1st is the biggest moving day of the year here. NoTimeMover has handled it before and is ready for it again.",
    metaTitle: 'Movers in Kenmore Square, Boston MA — NoTimeMover | Your Price',
    metaDescription: 'Kenmore Square movers near BU and Fenway. Set your budget before we call — fully insured, walk-ups welcome, September 1st ready.',
    neighborhoods: ['Fenway', 'Allston', 'Brighton', 'Back Bay', 'Coolidge Corner', 'Mission Hill', 'Brookline', 'Commonwealth Avenue area'],
    areasLabel: 'Kenmore Square & nearby neighborhoods',
    transit: 'Green Line (Kenmore, all branches)',
    housingStock: 'Dense student apartment buildings near BU and Fenway Park',
    driveTime: '~6 min from downtown Boston',
  },
  {
    slug: 'movers-longwood-ma',
    city: 'Longwood',
    headline: 'Longwood moves on your terms.',
    description: "The Longwood Medical Area draws a steady stream of medical students, residents, and staff who need flexible, no-fuss moving. NoTimeMover serves Longwood with same-day response and a fully insured crew — no matter how short the lease or how tight the timeline.",
    metaTitle: 'Movers in Longwood Medical Area, Boston — NoTimeMover | No Surprise Fees',
    metaDescription: 'Longwood Medical Area movers for students and staff. Set your budget upfront — fully insured crew, same-day response, walk-ups welcome.',
    neighborhoods: ['Mission Hill', 'Fenway', 'Jamaica Plain', 'Brookline', 'Roxbury', 'South End', 'Back Bay', 'Harvard Medical School area'],
    areasLabel: 'Longwood & Medical Area neighborhoods',
    transit: 'Green Line D/E branches (Longwood, Brookline Village)',
    housingStock: 'Apartments and short-term housing serving the Longwood Medical Area',
    driveTime: '~7 min from downtown Boston',
  },
  // ── Greater Boston suburbs ────────────────────────────────────────────────
  {
    slug: 'movers-boston-ma',
    city: 'Boston',
    headline: 'Boston moves on your terms.',
    description: 'Boston\'s busiest moving day is September 1st — but NoTimeMover is ready year-round. Set your budget before we contact you, skip the surprise quotes, and get moving.',
    metaTitle: 'Movers in Boston, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Boston\'s busiest moving day is September 1st. NoTimeMover is ready — set your budget upfront, skip the surprise quotes. Fully insured crew, walk-ups welcome.',
    neighborhoods: ['Back Bay', 'South End', 'Allston', 'Brighton', 'Fenway', 'Charlestown', 'Jamaica Plain', 'Dorchester', 'Somerville', 'Cambridge'],
    areasLabel: 'Boston neighborhoods & beyond',
    transit: 'All four MBTA rapid transit lines, plus regional and Amtrak rail',
    housingStock: 'Everything from triple-deckers to high-rise condos, block by block',
    driveTime: 'no commute — Boston is home base',
  },
  {
    slug: 'movers-cambridge-ma',
    city: 'Cambridge',
    headline: 'Cambridge moves on your terms.',
    description: 'Home to Harvard, MIT, and one of the densest apartment markets in New England. Cambridge triple-deckers, high-rises, and student moves are NoTimeMover\'s specialty.',
    metaTitle: 'Movers in Cambridge, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Moving near Harvard or MIT? Cambridge triple-deckers and high-rises are our specialty. Set your budget upfront — fully insured crew, same-day response.',
    neighborhoods: ['Somerville', 'Arlington', 'Belmont', 'Watertown', 'Allston', 'Brighton', 'Boston', 'Medford'],
    areasLabel: 'Cambridge & nearby neighborhoods',
    transit: 'Red Line (Harvard, Central, Kendall/MIT, Porter)',
    housingStock: 'Triple-deckers, historic multi-families, and new high-rises near MIT/Kendall',
    driveTime: '~8 min from downtown Boston',
  },
  {
    slug: 'movers-somerville-ma',
    city: 'Somerville',
    headline: 'Somerville moves on your terms.',
    description: 'Somerville is one of the most densely populated cities in the US — triple-deckers stacked on top of each other, Green Line stops, and a thriving arts crowd that moves often.',
    metaTitle: 'Movers in Somerville, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Somerville triple-deckers and condos. Set your budget before we call — fully insured crew, no stair fees, same-day response.',
    neighborhoods: ['Cambridge', 'Medford', 'Arlington', 'Malden', 'Everett', 'Charlestown', 'Boston', 'Davis Square'],
    areasLabel: 'Somerville & nearby areas',
    transit: 'Red Line (Davis, Porter) and the Green Line Extension (Union Sq, Ball Sq, Gilman Sq)',
    housingStock: 'Some of the densest triple-decker housing stock in New England',
    driveTime: '~10 min from downtown Boston',
  },
  {
    slug: 'movers-brookline-ma',
    city: 'Brookline',
    headline: 'Brookline moves on your terms.',
    description: 'Brookline\'s leafy streets, large homes, and proximity to Boston make it one of Greater Boston\'s most active moving markets. NoTimeMover serves Brookline with a fully insured crew.',
    metaTitle: 'Movers in Brookline, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Brookline movers for houses, condos, and apartments. Set your budget upfront — fully insured crew, same-day response, no surprise fees.',
    neighborhoods: ['Newton', 'Back Bay', 'Allston', 'Brighton', 'Fenway', 'Jamaica Plain', 'West Roxbury', 'Chestnut Hill'],
    areasLabel: 'Brookline & surrounding areas',
    transit: 'Green Line C/D branches (Coolidge Corner, Brookline Village, Chestnut Hill)',
    housingStock: 'Large single-family homes and pre-war apartment buildings',
    driveTime: '~10 min from downtown Boston',
  },
  {
    slug: 'movers-newton-ma',
    city: 'Newton',
    headline: 'Newton moves on your terms.',
    description: 'Newton\'s 13 villages and large residential homes mean bigger moves, more furniture, and more logistics. NoTimeMover handles Newton moves without hourly billing surprises.',
    metaTitle: 'Movers in Newton, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Newton movers for large homes, condos, and apartments across all 13 villages. Set your budget before we call — fully insured, same-day response.',
    neighborhoods: ['Brookline', 'Waltham', 'Needham', 'Wellesley', 'West Roxbury', 'Chestnut Hill', 'Watertown', 'Brighton'],
    areasLabel: 'Newton & surrounding neighborhoods',
    transit: 'Green Line D branch (Newton Centre, Newton Highlands, Waban, Woodland)',
    housingStock: 'Large single-family homes across Newton\'s 13 villages',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-quincy-ma',
    city: 'Quincy',
    headline: 'Quincy moves on your terms.',
    description: 'Quincy is one of the fastest-growing cities south of Boston — new condos downtown, family neighborhoods further out. NoTimeMover covers all of Quincy and the South Shore.',
    metaTitle: 'Movers in Quincy, MA — NoTimeMover | Your Price',
    metaDescription: 'Quincy movers for condos, apartments, and houses. Set your budget upfront — fully insured crew, same-day response. Serving Quincy and the South Shore.',
    neighborhoods: ['Braintree', 'Milton', 'Dorchester', 'South Boston', 'Weymouth', 'Randolph', 'Holbrook', 'Hingham'],
    areasLabel: 'Quincy & South Shore areas',
    transit: 'Red Line (Quincy Center, Wollaston, North Quincy, Quincy Adams)',
    housingStock: 'New downtown condo towers alongside classic South Shore family homes',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-medford-ma',
    city: 'Medford',
    headline: 'Medford moves on your terms.',
    description: 'Medford sits right at the crossroads of several major commuter corridors — close to Somerville, Cambridge, and Malden. NoTimeMover serves Medford with a fully insured crew.',
    metaTitle: 'Movers in Medford, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Medford movers, fully insured. Set your budget before we call — no surprise quotes. Serving Medford, Somerville, Malden, and all of Greater Boston.',
    neighborhoods: ['Somerville', 'Cambridge', 'Malden', 'Arlington', 'Everett', 'Woburn', 'Winchester', 'Tufts University area'],
    areasLabel: 'Medford & nearby areas',
    transit: 'Green Line Extension (Medford/Tufts, Ball Sq)',
    housingStock: 'Triple-deckers and single-families near Tufts University',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-malden-ma',
    city: 'Malden',
    headline: 'Malden moves on your terms.',
    description: 'Malden is one of Greater Boston\'s most diverse and active rental markets — affordable, Orange Line connected, and always moving. NoTimeMover is built for this.',
    metaTitle: 'Movers in Malden, MA — NoTimeMover | Affordable & Fast',
    metaDescription: 'Malden movers on your terms. Set your budget before we call — fully insured crew, same-day response. Serving Malden and Greater Boston.',
    neighborhoods: ['Medford', 'Somerville', 'Everett', 'Revere', 'Saugus', 'Woburn', 'Melrose', 'Malden Center'],
    areasLabel: 'Malden & surrounding areas',
    transit: 'Orange Line (Malden Center)',
    housingStock: 'Affordable multi-family apartment buildings — one of Greater Boston\'s most diverse rental markets',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-everett-ma',
    city: 'Everett',
    headline: 'Everett moves on your terms.',
    description: 'Everett has transformed rapidly over the past few years — new developments, a booming restaurant scene, and a steady flow of residents coming and going.',
    metaTitle: 'Movers in Everett, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Everett movers — new builds and older apartments. Set your budget before we reach out — fully insured, same-day response, no surprise fees.',
    neighborhoods: ['Somerville', 'Malden', 'Chelsea', 'East Boston', 'Revere', 'Medford', 'Charlestown', 'Encore area'],
    areasLabel: 'Everett & nearby areas',
    transit: 'Bus and Silver Line connections to Wellington and Assembly (Orange Line)',
    housingStock: 'Older triple-deckers alongside fast-moving new development',
    driveTime: '~10 min from downtown Boston',
  },
  {
    slug: 'movers-revere-ma',
    city: 'Revere',
    headline: 'Revere moves on your terms.',
    description: 'Revere Beach is the backdrop, but the city itself is a dense, growing rental market with strong demand for reliable movers. NoTimeMover serves Revere and the North Shore.',
    metaTitle: 'Movers in Revere, MA — NoTimeMover | Local & Insured',
    metaDescription: 'Revere movers, fully insured. Set your budget before we call — same-day response, no stair fees. Serving Revere and the North Shore.',
    neighborhoods: ['East Boston', 'Chelsea', 'Everett', 'Malden', 'Winthrop', 'Saugus', 'Lynn', 'Beachmont'],
    areasLabel: 'Revere & nearby areas',
    transit: 'Blue Line (Wonderland, Revere Beach, Beachmont)',
    housingStock: 'Dense apartment buildings near the beach, with growing rental demand',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-chelsea-ma',
    city: 'Chelsea',
    headline: 'Chelsea moves on your terms.',
    description: 'Chelsea is one of Greater Boston\'s most affordable cities — but it\'s changing fast. NoTimeMover serves Chelsea\'s apartments and condos with a fully insured crew.',
    metaTitle: 'Movers in Chelsea, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Chelsea movers, fully insured. Set your budget upfront — no hourly surprises. Serving Chelsea, East Boston, Revere, and all of Greater Boston.',
    neighborhoods: ['East Boston', 'Revere', 'Everett', 'Somerville', 'Charlestown', 'Winthrop', 'Malden', 'Downtown Boston'],
    areasLabel: 'Chelsea & nearby areas',
    transit: 'Silver Line SL3 and the Newburyport/Rockport Line commuter rail',
    housingStock: 'Affordable multi-family apartments in a rapidly changing housing market',
    driveTime: '~8 min from downtown Boston',
  },
  {
    slug: 'movers-waltham-ma',
    city: 'Waltham',
    headline: 'Waltham moves on your terms.',
    description: 'Waltham is a dense suburb with Brandeis University, a massive biotech corridor, and a steady flow of apartments turning over every year. NoTimeMover covers it all.',
    metaTitle: 'Movers in Waltham, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Waltham movers for apartments, condos, and houses. Set your budget before we call — fully insured, same-day response. Brandeis and beyond.',
    neighborhoods: ['Newton', 'Watertown', 'Belmont', 'Arlington', 'Lexington', 'Needham', 'Wellesley', 'Brighton'],
    areasLabel: 'Waltham & surrounding areas',
    transit: 'Fitchburg Line commuter rail (Waltham station)',
    housingStock: 'Dense apartments near Brandeis and the Route 128 biotech corridor',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-watertown-ma',
    city: 'Watertown',
    headline: 'Watertown moves on your terms.',
    description: 'Watertown sits between Cambridge, Newton, and Waltham — a convenient spot for commuters and a growing condo market. NoTimeMover has you covered.',
    metaTitle: 'Movers in Watertown, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Watertown movers for condos and apartments. Set your budget upfront — fully insured crew, same-day response. Between Cambridge, Newton, and Waltham.',
    neighborhoods: ['Cambridge', 'Newton', 'Waltham', 'Arlington', 'Belmont', 'Brighton', 'Allston', 'Brookline'],
    areasLabel: 'Watertown & nearby areas',
    transit: 'Bus routes to Harvard (Red Line); no direct rail station in town',
    housingStock: 'Growing condo development alongside older multi-family homes',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-arlington-ma',
    city: 'Arlington',
    headline: 'Arlington moves on your terms.',
    description: 'Arlington is one of the most desirable towns between Cambridge and Lexington — family-friendly, great schools, and a constant flow of new residents each year.',
    metaTitle: 'Movers in Arlington, MA — NoTimeMover | Your Price',
    metaDescription: 'Arlington movers for houses, condos, and apartments. Set your budget before we call — fully insured crew, same-day response, no surprise fees.',
    neighborhoods: ['Cambridge', 'Belmont', 'Lexington', 'Medford', 'Somerville', 'Watertown', 'Waltham', 'Winchester'],
    areasLabel: 'Arlington & nearby towns',
    transit: 'Bus routes to Alewife (Red Line); no direct rail station in town',
    housingStock: 'Single- and two-family homes in a family-oriented housing market',
    driveTime: '~12 min from downtown Boston',
  },
  {
    slug: 'movers-belmont-ma',
    city: 'Belmont',
    headline: 'Belmont moves on your terms.',
    description: 'Belmont is a quiet residential town with large homes and an affluent commuter base. NoTimeMover handles Belmont moves with the care they deserve — no surprise fees.',
    metaTitle: 'Movers in Belmont, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Belmont movers for houses and condos. Set your budget before we call — fully insured, same-day response, no hourly billing surprises.',
    neighborhoods: ['Cambridge', 'Arlington', 'Watertown', 'Waltham', 'Lexington', 'Medford', 'Somerville', 'Brighton'],
    areasLabel: 'Belmont & nearby towns',
    transit: 'Fitchburg Line commuter rail (Belmont Center, Waverley)',
    housingStock: 'Larger single-family homes on quiet residential streets',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-needham-ma',
    city: 'Needham',
    headline: 'Needham moves on your terms.',
    description: 'Needham\'s high home values and large floor plans mean bigger moves. NoTimeMover handles full house moves, condo relocations, and everything in between — tell us your budget.',
    metaTitle: 'Movers in Needham, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Needham movers for full house and condo moves. Set your budget upfront — fully insured crew, same-day response, no hidden fees on move day.',
    neighborhoods: ['Newton', 'Dedham', 'Wellesley', 'West Roxbury', 'Brookline', 'Natick', 'Norwood', 'Walpole'],
    areasLabel: 'Needham & surrounding towns',
    transit: 'Needham Line commuter rail (Needham Center, Needham Heights)',
    housingStock: 'Large single-family homes on bigger lots',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-dedham-ma',
    city: 'Dedham',
    headline: 'Dedham moves on your terms.',
    description: 'Dedham is a growing suburb southwest of Boston — easy highway access, solid schools, and a steady housing market that keeps movers busy year-round.',
    metaTitle: 'Movers in Dedham, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Dedham movers for houses, condos, and apartments. Set your budget before we call — fully insured, same-day response, no stair fees.',
    neighborhoods: ['Norwood', 'Needham', 'West Roxbury', 'Milton', 'Westwood', 'Canton', 'Hyde Park', 'Roslindale'],
    areasLabel: 'Dedham & nearby towns',
    transit: 'Franklin Line commuter rail (Dedham Corporate Center, Endicott)',
    housingStock: 'Single-family homes and townhouse developments',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-braintree-ma',
    city: 'Braintree',
    headline: 'Braintree moves on your terms.',
    description: 'Braintree is the southern anchor of the Red Line — great highway access, solid neighborhoods, and a mix of condos and single-family homes that turn over regularly.',
    metaTitle: 'Movers in Braintree, MA — NoTimeMover | Your Price',
    metaDescription: 'Braintree movers for condos, houses, and apartments. Set your budget upfront — fully insured crew, same-day response. South Shore and Boston.',
    neighborhoods: ['Quincy', 'Weymouth', 'Randolph', 'Milton', 'Holbrook', 'Norwell', 'Avon', 'Holbrook'],
    areasLabel: 'Braintree & South Shore areas',
    transit: 'Red Line southern terminus (Braintree station)',
    housingStock: 'Mix of condos near the T and single-family homes further out',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-milton-ma',
    city: 'Milton',
    headline: 'Milton moves on your terms.',
    description: 'Milton sits between Boston and Quincy — quiet, suburban, and full of large family homes. NoTimeMover handles residential moves in Milton without hourly billing surprises.',
    metaTitle: 'Movers in Milton, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Milton residential movers for houses and condos. Set your budget before we call — fully insured, same-day response, no surprise fees.',
    neighborhoods: ['Quincy', 'Dorchester', 'Hyde Park', 'Braintree', 'Canton', 'Stoughton', 'Randolph', 'East Milton'],
    areasLabel: 'Milton & nearby towns',
    transit: 'Mattapan Trolley (Central Ave, Valley Rd, Capen St)',
    housingStock: 'Large single-family homes — one of the South Shore\'s quieter towns',
    driveTime: '~18 min from downtown Boston',
  },
  {
    slug: 'movers-lynn-ma',
    city: 'Lynn',
    headline: 'Lynn moves on your terms.',
    description: 'Lynn is one of the North Shore\'s most affordable cities and one of its most active rental markets. NoTimeMover serves Lynn with a fully insured crew and same-day response.',
    metaTitle: 'Movers in Lynn, MA — NoTimeMover | Affordable & Insured',
    metaDescription: 'Lynn movers, fully insured. Set your budget before we call — no hourly surprises. Serving Lynn, Saugus, Peabody, and the North Shore.',
    neighborhoods: ['Saugus', 'Peabody', 'Salem', 'Revere', 'Malden', 'Everett', 'Swampscott', 'Nahant'],
    areasLabel: 'Lynn & North Shore areas',
    transit: 'Newburyport/Rockport Line commuter rail (Lynn station)',
    housingStock: 'Dense multi-family housing — one of the North Shore\'s most active rental markets',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-winthrop-ma',
    city: 'Winthrop',
    headline: 'Winthrop moves on your terms.',
    description: 'Winthrop is a small peninsula town east of Boston with a tight-knit community and a limited supply of housing that drives steady moving demand.',
    metaTitle: 'Movers in Winthrop, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Winthrop movers, fully insured. Set your budget before we call — same-day response, no hidden fees. East of Boston, close to Logan.',
    neighborhoods: ['East Boston', 'Revere', 'Chelsea', 'Everett', 'Malden', 'Swampscott', 'Lynn', 'Beachmont'],
    areasLabel: 'Winthrop & nearby areas',
    transit: 'Bus connections to Orient Heights (Blue Line); no direct rail station in town',
    housingStock: 'Tight-knit peninsula housing stock with limited new construction',
    driveTime: '~15 min from downtown Boston',
  },
  {
    slug: 'movers-woburn-ma',
    city: 'Woburn',
    headline: 'Woburn moves on your terms.',
    description: 'Woburn is a fast-growing suburb north of Boston — close to Route 128, with new apartment complexes and established neighborhoods all moving regularly.',
    metaTitle: 'Movers in Woburn, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Woburn movers for apartments, condos, and houses. Set your budget before we call — fully insured crew, same-day response, no surprise fees.',
    neighborhoods: ['Medford', 'Malden', 'Burlington', 'Winchester', 'Stoneham', 'Lexington', 'Woburn Center', 'Wilmington'],
    areasLabel: 'Woburn & nearby towns',
    transit: 'Lowell Line commuter rail (Anderson Regional Transportation Center)',
    housingStock: 'Mix of apartment complexes and single-family homes near Route 128',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-burlington-ma',
    city: 'Burlington',
    headline: 'Burlington moves on your terms.',
    description: 'Burlington is a thriving Route 128 suburb — lots of new apartment development, proximity to tech campuses, and a steady flow of residents moving in and out.',
    metaTitle: 'Movers in Burlington, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Burlington movers for new apartments and established homes. Set your budget upfront — fully insured, same-day response, no hourly billing surprises.',
    neighborhoods: ['Woburn', 'Lexington', 'Wilmington', 'Bedford', 'Billerica', 'Waltham', 'Stoneham', 'Route 128 corridor'],
    areasLabel: 'Burlington & nearby towns',
    transit: 'No direct rail station; served by Routes 128/95 and local bus',
    housingStock: 'New apartment development near the tech corridor, plus single-family neighborhoods',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-lexington-ma',
    city: 'Lexington',
    headline: 'Lexington moves on your terms.',
    description: 'Lexington is one of Greater Boston\'s most prestigious suburbs — large homes, top-rated schools, and a housing market that keeps movers busy. NoTimeMover handles it with care.',
    metaTitle: 'Movers in Lexington, MA — NoTimeMover | Your Budget',
    metaDescription: 'Lexington movers for large homes and condos. Set your budget before we call — fully insured crew, same-day response, no hidden fees.',
    neighborhoods: ['Arlington', 'Belmont', 'Waltham', 'Burlington', 'Bedford', 'Concord', 'Lincoln', 'Winchester'],
    areasLabel: 'Lexington & surrounding towns',
    transit: 'Bus routes to Alewife (Red Line); no direct rail station in town',
    housingStock: 'Large single-family homes in one of Greater Boston\'s top-rated school districts',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-framingham-ma',
    city: 'Framingham',
    headline: 'Framingham moves on your terms.',
    description: 'Framingham is a hub city along Route 9 — a mix of apartments, condos, and single-family homes that makes it one of MetroWest\'s busiest moving markets.',
    metaTitle: 'Movers in Framingham, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Framingham movers for apartments, condos, and houses. Set your budget before we call — fully insured crew, same-day response, MetroWest and beyond.',
    neighborhoods: ['Natick', 'Ashland', 'Sudbury', 'Marlborough', 'Southborough', 'Holliston', 'Hopkinton', 'Sherborn'],
    areasLabel: 'Framingham & MetroWest areas',
    transit: 'Framingham/Worcester Line commuter rail (Framingham station)',
    housingStock: 'Mix of apartments, condos, and single-family homes along Route 9',
    driveTime: '~25 min from downtown Boston',
  },
  {
    slug: 'movers-natick-ma',
    city: 'Natick',
    headline: 'Natick moves on your terms.',
    description: 'Natick is a growing MetroWest town with a mix of new condos, classic New England homes, and a steady flow of residents relocating to and from Greater Boston.',
    metaTitle: 'Movers in Natick, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Natick movers for condos, houses, and apartments. Set your budget upfront — fully insured crew, same-day response, no surprise fees on move day.',
    neighborhoods: ['Framingham', 'Wellesley', 'Needham', 'Ashland', 'Wayland', 'Sherborn', 'Holliston', 'Route 9 corridor'],
    areasLabel: 'Natick & MetroWest towns',
    transit: 'Framingham/Worcester Line commuter rail (Natick Center, West Natick)',
    housingStock: 'New condo development alongside classic New England single-families',
    driveTime: '~25 min from downtown Boston',
  },
  {
    slug: 'movers-wellesley-ma',
    city: 'Wellesley',
    headline: 'Wellesley moves on your terms.',
    description: 'Wellesley is one of the most desirable towns in Greater Boston — large homes, Wellesley College, and a housing market that demands a crew you can trust.',
    metaTitle: 'Movers in Wellesley, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Wellesley movers for large homes and condos. Set your budget before we call — fully insured crew, same-day response, handled with care.',
    neighborhoods: ['Needham', 'Newton', 'Natick', 'Weston', 'Dedham', 'Westwood', 'Dover', 'Route 9 corridor'],
    areasLabel: 'Wellesley & surrounding towns',
    transit: 'Framingham/Worcester Line commuter rail (Wellesley Sq, Wellesley Hills, Wellesley Farms)',
    housingStock: 'Large historic homes near Wellesley College',
    driveTime: '~20 min from downtown Boston',
  },
  {
    slug: 'movers-marlborough-ma',
    city: 'Marlborough',
    headline: 'Marlborough moves on your terms.',
    description: 'Marlborough sits along the Route 20/I-495 corporate corridor — apartment complexes, corporate relocations, and a historic downtown that all turn over regularly. NoTimeMover covers Marlborough and the rest of MetroWest.',
    metaTitle: 'Movers in Marlborough, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Marlborough movers for apartments, condos, and houses. Set your budget before we call — fully insured crew, same-day response, MetroWest and beyond.',
    neighborhoods: ['Northborough', 'Southborough', 'Hudson', 'Framingham', 'Sudbury', 'Berlin', 'Hopkinton', 'Westborough'],
    areasLabel: 'Marlborough & MetroWest areas',
    transit: 'No direct rail station; served by Route 20/I-495 and MetroWest Regional Transit Authority buses',
    housingStock: 'Mix of historic multi-families downtown and newer apartment complexes near the 495 corporate corridor',
    driveTime: '~40 min from downtown Boston',
  },
  {
    slug: 'movers-peabody-ma',
    city: 'Peabody',
    headline: 'Peabody moves on your terms.',
    description: 'Peabody is one of the North Shore\'s largest cities — affordable housing, good highway access, and a steady rental market. NoTimeMover serves Peabody with same-day response.',
    metaTitle: 'Movers in Peabody, MA — NoTimeMover | Your Price',
    metaDescription: 'Peabody movers, fully insured. Set your budget before we call — no hourly surprises. Serving Peabody, Salem, Beverly, and the North Shore.',
    neighborhoods: ['Salem', 'Beverly', 'Lynn', 'Danvers', 'Marblehead', 'Swampscott', 'Saugus', 'Topsfield'],
    areasLabel: 'Peabody & North Shore areas',
    transit: 'No direct rail station; nearby Salem stop on the Newburyport/Rockport Line',
    housingStock: 'Affordable multi-family housing and single-family neighborhoods',
    driveTime: '~25 min from downtown Boston',
  },
  {
    slug: 'movers-salem-ma',
    city: 'Salem',
    headline: 'Salem moves on your terms.',
    description: 'Salem is one of the most vibrant cities on the North Shore — historic, dense, and growing. NoTimeMover handles Salem\'s Victorian homes, condos, and apartments alike.',
    metaTitle: 'Movers in Salem, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Salem movers for Victorians, condos, and apartments. Set your budget upfront — fully insured crew, same-day response. North Shore covered.',
    neighborhoods: ['Peabody', 'Beverly', 'Marblehead', 'Swampscott', 'Lynn', 'Danvers', 'Ipswich', 'Hamilton'],
    areasLabel: 'Salem & North Shore areas',
    transit: 'Newburyport/Rockport Line commuter rail (Salem station)',
    housingStock: 'Historic Victorian homes and a dense, walkable downtown',
    driveTime: '~25 min from downtown Boston',
  },
  {
    slug: 'movers-beverly-ma',
    city: 'Beverly',
    headline: 'Beverly moves on your terms.',
    description: 'Beverly is a growing North Shore city with a mix of commuters, artists, and families. NoTimeMover serves Beverly with a fully insured crew and no-nonsense pricing.',
    metaTitle: 'Movers in Beverly, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Beverly movers, fully insured. Set your budget before we call — same-day response, no hidden fees. North Shore and Greater Boston.',
    neighborhoods: ['Salem', 'Peabody', 'Danvers', 'Wenham', 'Hamilton', 'Gloucester', 'Manchester', 'Marblehead'],
    areasLabel: 'Beverly & North Shore towns',
    transit: 'Newburyport/Rockport Line commuter rail (Beverly, Montserrat, Prides Crossing)',
    housingStock: 'Mix of coastal homes and denser near-downtown housing',
    driveTime: '~30 min from downtown Boston',
  },
  // ── Extended MA ───────────────────────────────────────────────────────────
  {
    slug: 'movers-worcester-ma',
    city: 'Worcester',
    headline: 'Worcester moves on your terms.',
    description: 'Worcester is Massachusetts\' second-largest city — home to Clark, WPI, Holy Cross, and a large apartment market. NoTimeMover handles Worcester moves without hourly billing surprises.',
    metaTitle: 'Movers in Worcester, MA — NoTimeMover | No Surprise Fees',
    metaDescription: "Worcester's second-largest city deserves straightforward moving. Set your budget before we call — no hourly surprises. Fully insured crew, same-day response.",
    neighborhoods: ['Shrewsbury', 'Millbury', 'Auburn', 'Grafton', 'Northborough', 'Westborough', 'Paxton', 'Holden'],
    areasLabel: 'Worcester & surrounding cities',
    transit: 'Framingham/Worcester Line commuter rail (Union Station), I-90/I-290',
    housingStock: 'Triple-deckers and apartments near Clark, WPI, and Holy Cross',
    driveTime: '~50 min from downtown Boston',
  },
  {
    slug: 'movers-lowell-ma',
    city: 'Lowell',
    headline: 'Lowell moves on your terms.',
    description: 'Lowell is a diverse, growing city along the Merrimack — UMass Lowell, a revitalized downtown, and a large rental market. NoTimeMover serves Lowell with same-day response.',
    metaTitle: 'Movers in Lowell, MA — NoTimeMover | Local & Affordable',
    metaDescription: 'Moving near UMass Lowell or anywhere in the Mill City? Set your budget upfront and we tell you exactly what it covers. Fully insured crew, same-day response.',
    neighborhoods: ['Chelmsford', 'Dracut', 'Tewksbury', 'Billerica', 'Wilmington', 'Methuen', 'Lawrence', 'Haverhill'],
    areasLabel: 'Lowell & Merrimack Valley areas',
    transit: 'Lowell Line commuter rail (Lowell station), Route 495/93',
    housingStock: 'Historic mill-city apartments and a revitalized downtown near UMass Lowell',
    driveTime: '~40 min from downtown Boston',
  },
  {
    slug: 'movers-springfield-ma',
    city: 'Springfield',
    headline: 'Springfield moves on your terms.',
    description: 'Springfield is the anchor of Western Massachusetts — the biggest city for 100 miles in any direction and a major hub for both local and out-of-state moves.',
    metaTitle: 'Movers in Springfield, MA — NoTimeMover | Your Budget',
    metaDescription: "Western MA's movers for local and out-of-state moves. Set your budget before we reach out — no surprise quotes. Fully insured, same-day response.",
    neighborhoods: ['Chicopee', 'Holyoke', 'Ludlow', 'Agawam', 'West Springfield', 'Longmeadow', 'East Longmeadow', 'Wilbraham'],
    areasLabel: 'Springfield & Pioneer Valley areas',
    transit: 'Amtrak service, I-91/I-90 (Mass Pike)',
    housingStock: 'Diverse mix of triple-deckers, apartments, and single-family homes',
    driveTime: '~90 min from downtown Boston',
  },
  {
    slug: 'movers-lawrence-ma',
    city: 'Lawrence',
    headline: 'Lawrence moves on your terms.',
    description: 'Lawrence is a dense Merrimack Valley city with one of the most active rental markets in the region. NoTimeMover handles Lawrence moves quickly and without surprise fees.',
    metaTitle: 'Movers in Lawrence, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Lawrence movers, fully insured. Set your budget before we call — no surprise quotes, same-day response. Serving Lawrence and the Merrimack Valley.',
    neighborhoods: ['Methuen', 'Andover', 'North Andover', 'Haverhill', 'Lowell', 'Salem NH', 'Bradford', 'Dracut'],
    areasLabel: 'Lawrence & Merrimack Valley areas',
    transit: 'Haverhill Line commuter rail (Lawrence station), Route 495/93',
    housingStock: 'Dense mill-city apartment buildings — one of the Merrimack Valley\'s busiest rental markets',
    driveTime: '~35 min from downtown Boston',
  },
  {
    slug: 'movers-haverhill-ma',
    city: 'Haverhill',
    headline: 'Haverhill moves on your terms.',
    description: 'Haverhill is a growing Merrimack Valley city with a revitalized downtown and an active housing market. NoTimeMover serves Haverhill with fully insured crews.',
    metaTitle: 'Movers in Haverhill, MA — NoTimeMover | No Hidden Fees',
    metaDescription: 'Haverhill movers, fully insured. Set your budget before we contact you — same-day response, no surprise fees. Merrimack Valley covered.',
    neighborhoods: ['Lawrence', 'Methuen', 'Bradford', 'Amesbury', 'Salisbury', 'Newburyport', 'Groveland', 'Plaistow NH'],
    areasLabel: 'Haverhill & nearby towns',
    transit: 'Haverhill Line commuter rail (Haverhill station), Route 495',
    housingStock: 'Revitalized downtown apartments alongside single-family neighborhoods',
    driveTime: '~40 min from downtown Boston',
  },
  {
    slug: 'movers-brockton-ma',
    city: 'Brockton',
    headline: 'Brockton moves on your terms.',
    description: 'Brockton is one of the most populous cities in southeastern Massachusetts — a large, diverse rental market with steady moving demand year-round.',
    metaTitle: 'Movers in Brockton, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Brockton movers, fully insured. Set your budget before we call — no hourly surprises, same-day response. Serving Brockton and southeastern MA.',
    neighborhoods: ['Stoughton', 'Avon', 'Easton', 'West Bridgewater', 'Bridgewater', 'Abington', 'Whitman', 'Randolph'],
    areasLabel: 'Brockton & southeastern MA areas',
    transit: 'Middleborough/Lakeville Line commuter rail (Brockton station), Route 24',
    housingStock: 'Large, diverse mix of multi-family and single-family housing',
    driveTime: '~30 min from downtown Boston',
  },
  {
    slug: 'movers-new-bedford-ma',
    city: 'New Bedford',
    headline: 'New Bedford moves on your terms.',
    description: 'New Bedford is the largest city on the SouthCoast — a historic whaling city with a large working-class rental market and strong moving demand throughout the year.',
    metaTitle: 'Movers in New Bedford, MA — NoTimeMover | Your Price',
    metaDescription: 'New Bedford movers, fully insured. Set your budget upfront — no surprise fees, same-day response. SouthCoast MA covered.',
    neighborhoods: ['Dartmouth', 'Fairhaven', 'Acushnet', 'Fall River', 'Taunton', 'Wareham', 'Marion', 'Mattapoisett'],
    areasLabel: 'New Bedford & SouthCoast areas',
    transit: 'South Coast Rail commuter service to Boston, I-195',
    housingStock: 'Historic working-class multi-family homes near the harbor',
    driveTime: '~60 min from downtown Boston',
  },
  {
    slug: 'movers-fall-river-ma',
    city: 'Fall River',
    headline: 'Fall River moves on your terms.',
    description: 'Fall River sits right on the Rhode Island border — close enough to Providence for out-of-state demand and large enough for a thriving local rental market.',
    metaTitle: 'Movers in Fall River, MA — NoTimeMover | No Surprise Fees',
    metaDescription: 'Fall River movers, fully insured. Set your budget before we call — same-day response, no hidden fees. MA/RI border and beyond.',
    neighborhoods: ['New Bedford', 'Taunton', 'Swansea', 'Somerset', 'Dighton', 'Seekonk', 'Attleboro', 'Providence RI area'],
    areasLabel: 'Fall River & SouthCoast areas',
    transit: 'South Coast Rail commuter service to Boston, I-195/Route 24',
    housingStock: 'Dense multi-family housing near the Rhode Island border',
    driveTime: '~60 min from downtown Boston',
  },
  {
    slug: 'movers-taunton-ma',
    city: 'Taunton',
    headline: 'Taunton moves on your terms.',
    description: 'Taunton is a growing city at the crossroads of southeastern Massachusetts — midway between Boston, Providence, and New Bedford, with a steady housing market.',
    metaTitle: 'Movers in Taunton, MA — NoTimeMover | No Surprise Quotes',
    metaDescription: 'Taunton movers, fully insured. Set your budget upfront — no hourly surprises, same-day response. Southeastern MA and beyond.',
    neighborhoods: ['Brockton', 'Raynham', 'Easton', 'Norton', 'Berkley', 'Dighton', 'Bridgewater', 'Attleboro'],
    areasLabel: 'Taunton & southeastern MA areas',
    transit: 'Car-dependent, with commuter rail expansion underway; Route 24/495',
    housingStock: 'Mix of single-family homes and multi-family housing',
    driveTime: '~45 min from downtown Boston',
  },
  {
    slug: 'movers-plymouth-ma',
    city: 'Plymouth',
    headline: 'Plymouth moves on your terms.',
    description: 'Plymouth is America\'s hometown and one of the fastest-growing towns on the South Shore — new construction, waterfront condos, and a busy seasonal moving market.',
    metaTitle: 'Movers in Plymouth, MA — NoTimeMover | Set Your Budget',
    metaDescription: 'Plymouth movers for new construction and established homes. Set your budget before we call — fully insured, same-day response, South Shore covered.',
    neighborhoods: ['Kingston', 'Duxbury', 'Marshfield', 'Wareham', 'Carver', 'Middleborough', 'Pembroke', 'Hanson'],
    areasLabel: 'Plymouth & South Shore towns',
    transit: 'Kingston/Plymouth Line commuter rail (Cordage Park, Plymouth)',
    housingStock: 'New waterfront condos and established single-family neighborhoods',
    driveTime: '~45 min from downtown Boston',
  },
]

export function getLocation(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug)
}

export function getAllSlugs(): string[] {
  return locations.map((l) => l.slug)
}
